version: 2
jobs:
  test:
    docker:
      - image: bdfoster/nvm
    steps:
      - checkout
      - run:
          name: Test
        command: |
          nvm install
          nvm use
          npm test
  release:
    docker:
      - image: bdfoster/nvm
    steps:
      - checkout
      - run:
          name: Test
        command: |
          nvm install
          nvm use
          npm test

workflows:
  version: 2
  build_and_test:
    jobs:
      - test:
          requires:
            - test
          filters:
            branches:
              only: master
